// packages/vue-app/src/components/ThemeToggle.vue
<template>
  <button
    @click="toggle"
    class="
      rounded-xl border px-3 py-1.5
      bg-white text-gray-800 border-gray-300
      hover:bg-gray-50
      dark:bg-gray-900 dark:text-gray-100 dark:border-gray-700 dark:hover:bg-gray-800
      focus:outline-none focus-visible:ring-2 focus-visible:ring-primary/60
    "
    :aria-pressed="isDark"
    :title="isDark ? 'Switch to Light' : 'Switch to Dark'"
  >
    {{ isDark ? '☾ Dark' : '☀︎ Light' }}
  </button>
</template>

<script setup lang="ts">
import { onMounted, ref } from 'vue'

const isDark = ref(false)
onMounted(() => {
  isDark.value = document.documentElement.classList.contains('dark')
})

function toggle() {
  isDark.value = !isDark.value
  document.documentElement.classList.toggle('dark', isDark.value)
}
</script>

<style scoped></style>

// packages/react-app/src/components/ThemeToggle.tsx
import { useEffect, useState } from 'react'

export default function ThemeToggle() {
  const [isDark, setIsDark] = useState(false)

  useEffect(() => {
    const saved = localStorage.getItem('theme:dark') === '1'
    setIsDark(saved)
    document.documentElement.classList.toggle('dark', saved)
  }, [])

  const toggle = () => {
    const next = !isDark
    setIsDark(next)
    document.documentElement.classList.toggle('dark', next)
    localStorage.setItem('theme:dark', next ? '1' : '0')
  }

  return (
    <button
      onClick={toggle}
      aria-pressed={isDark}
      title={isDark ? 'Switch to Light' : 'Switch to Dark'}
      className="rounded-xl border px-3 py-1.5
             bg-surface text-on-surface border-gray-300 hover:bg-gray-50
             dark:border-gray-700 dark:hover:bg-gray-800
             focus:outline-none focus-visible:ring-2 focus-visible:ring-primary/60"
    >
      {isDark ? '☾ Dark' : '☀︎ Light'}
    </button>
  )
}
